apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pmem-csi-pvc-ext4
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: pmem-csi-sc-ext4 # defined in pmem-storageclass-ext4.yaml
---
kind: Pod
apiVersion: v1
metadata:
  name: redis-with-pba
spec:
  containers:
    - name: redis-with-pba 
      image: pmem-redis
      args: ["yes"]
      ports:
      - containerPort: 6379
      resources:
        limits:
          cpu: "1000m"
          memory: "16Gi"
        requests:
          cpu: "1000m"
          memory: "16Gi"
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-volume
  volumes:
  - name: my-csi-volume
    persistentVolumeClaim:
      claimName: pmem-csi-pvc-ext4
