---
kind: Pod
apiVersion: v1
metadata:
  name: redis-volatile
spec:
  containers:
    - name: redis-volatile
      image: pmem-redis
      args: ["noaof"]
      ports:
      - containerPort: 6379
      resources:
        limits:
          cpu: "1000m"
          memory: "16Gi"
        requests:
          cpu: "1000m"
          memory: "16Gi"
