---
kind: Pod
apiVersion: v1
metadata:
  name: redis-aof
spec:
  containers:
    - name: redis-aof
      image: pmem-redis
      imagePullPolicy: Never
      args: ["no"]
      ports:
      - containerPort: 6379
      resources:
        limits:
          cpu: "1000m"
          memory: "16Gi"
        requests:
          cpu: "1000m"
          memory: "16Gi"
